Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dataPatiens = {
    'name':['Jack','Jim','Mary'],
    'gender': ['M', 'M','F '],
    'fever': ['Y','Y','Y'],
    'cough': ['N','Y','N' ],
    'test-1': ['P','N','P' ],
    'test-2': ['N','N','N' ],
    'test-3': ['N','N','P' ],
    'test-4': ['N','N','N' ]}
dataShow = pd.DataFrame(dataPatiens)
print("Relational Table Where Patients Are Described by Binary Attributes\n")
dataShow


------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-3-0a0637e5eae9>[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m     [0;34m'test-3'[0m[0;34m:[0m [0;34m[[0m[0;34m'N'[0m[0;34m,[0m[0;34m'N'[0m[0;34m,[0m[0;34m'P'[0m [0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m     'test-4': ['N','N','N' ]}
[0;32m---> 10[0;31m [0mdataShow[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mdataPatiens[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m [0mprint[0m[0;34m([0m[0;34m"Relational Table Where Patients Are Described by Binary Attributes\n"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0mdataShow[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pd' is not defined
NameError: name 'pd' is not defined

